#!/bin/bash 
variabile=$(lsblk -f /dev/sdb 2>/dev/null ; echo $? | grep -Eo '[0-9]{1,4}')
variabile2=$(mount | grep '/dev/sdb' >>/dev/null ; echo $? | grep -Eo '[0-9]{1,4}')
{
if [ $variabile2 -eq 0 ] 2>/dev/null
then
echo -e "\e[31mERRORE\e[0m\nChiavetta già montata"
else 
if [ $variabile -eq 32 ] 2>/dev/null
then   
sudo systemctl kill udisks2 2>/dev/null
echo "Inserisci la chiavetta"
sleep 5
fi
sudo mount /dev/sdb1 /run/mount 2>/dev/null 
if [ $? -eq 0 ] 
then 
echo "Device montato in /run/mount da $USER" 
else 
echo -e "\e[31mImpossibile eseguire il comando:\e[0m\nChiavetta non inserita o non leggibile\n"
fi
fi
}

